// <auto-generated />
using KalapulgaMerge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KalapulgaMerge.Data.Migrations
{
    [DbContext(typeof(KalapulkDbContext))]
    [Migration("20260504123217_init5")]
    partial class init5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KalapulgaMerge.Core.Domain.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            ImageUrl = "lib/defaultassets/image/shop1.png",
                            IsAvailable = true,
                            Name = "Punane müts",
                            Price = 500m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            ImageUrl = "lib/defaultassets/image/shop2.png",
                            IsAvailable = true,
                            Name = "Sinine müts",
                            Price = 500m,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            ImageUrl = "lib/defaultassets/image/shop3.png",
                            IsAvailable = true,
                            Name = "Ümarad prillid",
                            Price = 750m,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            ImageUrl = "lib/defaultassets/image/shop4.png",
                            IsAvailable = true,
                            Name = "Päikeseprillid",
                            Price = 750m,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Kuldne värv",
                            Price = 1000m,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Hõbedane värv",
                            Price = 1000m,
                            Type = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
